### ISSUE TITLE
仪表盘setRealTimeValue放到回调函数，会出现指针绘制重复的问题

### ISSUE THREAD

**Issue by githubwing** [woxingxiao/DashboardViewDemo#1]
如按钮onClick监听 或者是网络访问回调都会绘制重复，我是一个新手..也不懂怎么解决，求教。

**Comment by woxingxiao** [comment]
已修复，谢谢反馈。我用canvas.drawPath绘制的指针，实时值改变后指针指向改变，但未调用path.reset()清空原来的路径，所以出现两条指针了。
