### ISSUE TITLE
代码中设置setRealTimeValue不起作用

### ISSUE THREAD

**Issue by ayuhani** [woxingxiao/DashboardViewDemo#2]
我用了你的这个控件，在xml中设置RealTimeValue是可以正常显示的，但是在代码中通过对象调用setRealTimeValue时，指针一直指向0.然后我运行了你的代码，发现同样第四个指向0，前三个通过xml设置的都正常显示，不知道这是什么问题呀。

**Comment by woxingxiao** [comment]
嗯是的，你调用`setRealTimeValue(float realTimeValue, true)`这个方法就能更新。我有时间就修复，感谢反馈：）

**Comment by ayuhani** [comment]
经过我的测试，得到下面结果，比较乱
首先我设置的最大值是10，第一次调用setRealTimeValue(float realTimeValue, true)时,0-5的范围确实能够正确显示。可是从6开始，指向+1的位置，例如设置setRealTimeValue(6, true)，表盘指向7；setRealTimeValue(9, true)，表盘指向10.
然后当数据更新之后，第二次调用setRealTimeValue(newValue, true)时，依然是没有作用，表盘指向第一次设置的值。

**Comment by woxingxiao** [comment]
bug已修复，你看是否解决了你遇到的问题

**Comment by ayuhani** [comment]
完美解决，帮了大忙了，感谢感谢

**Comment by woxingxiao** [comment]
客气了，互相学习
