### ISSUE TITLE
min为负数，max为正数时，刻度计算有误

### ISSUE THREAD

**Issue by Saxxhw** [woxingxiao/DashboardViewDemo#3]
如题，设置最小值为-90，最大值为90，表盘显示的刻度分别为-90，36，72，108，144，90
`private String[] getMeasureNumbers() {
        String[] strings = new String[mBigSliceCount + 1];
        for (int i = 0; i <= mBigSliceCount; i++) {
            if (i == 0) {
                strings[i] = String.valueOf(mMinValue);
            } else if (i == mBigSliceCount) {
                strings[i] = String.valueOf(mMaxValue);
            } else {
                strings[i] = String.valueOf(((mMaxValue - mMinValue) / mBigSliceCount) * i);
            }
        }

        return strings;
    }`
这个计算刻度的方法应该修改一下

**Comment by Saxxhw** [comment]
`private String[] getMeasureNumbers() {
        String[] strings = new String[mBigSliceCount + 1];
        for (int i = 0; i <= mBigSliceCount; i++) {
            if (i == 0) {
                strings[i] = String.valueOf(mMinValue);
            } else if (i == mBigSliceCount) {
                strings[i] = String.valueOf(mMaxValue);
            } else {
                int average = (mMaxValue - mMinValue) / mBigSliceCount;
                strings[i] = String.valueOf(mMinValue + average * i);
            }
        }

        return strings;
    }`
我改成这样测试了一下，不知道有没有问题，耐心等待大神的修改方案~~

**Comment by woxingxiao** [comment]
相信最新的`DashboardView1`已经解决了这个问题
