### ISSUE TITLE
炫酷汽车速度仪表这个view，仪盘表绘制偏移

### ISSUE THREAD

**Issue by NicodeLee** [woxingxiao/DashboardViewDemo#4]
布局是横屏的，属性自适应。另外如果是固定宽高是否能适应。
![pianyi](http://7xlc12.com1.z0.glb.clouddn.com/%E5%81%8F%E7%A7%BB.png)  

[或者看截图如下](http://7xlc12.com1.z0.glb.clouddn.com/%E5%81%8F%E7%A7%BB.png)

demo也发现需要触发点击事件控件才能正常绘制显示。

**Comment by woxingxiao** [comment]
这个项目不作为lib发布，如果你有需求可以自行完善哦
